const express=require('express');
const cors=require('cors');
const dotenv=require('dotenv');
const connectDB=require('./config/db');
dotenv.config();
connectDB();
const app=express();
app.use(cors());
app.use(express.json());
app.use('/api/auth',require('./router/authRouter'));
app.use('/api/cats',require('./router/catRouter'));
app.listen(process.env.PORT||5000);